branches:
  only:
    - master
    - travis

git:
    depth: 1
    submodules: false

language: cpp

matrix:
   include:
     - name: "linux-gcc"
       os: linux
       dist: xenial
       compiler: gcc

     - name: "linux-clang"
       os: linux
       dist: xenial
       compiler: clang
       before_install:
         - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

     - name: "osx"
       os: osx

sudo: required

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev
      - z3
      - libz3-dev

  homebrew:
    update: true
    packages:
      - boost
      - boost-python
      - z3
   
script:
  - cd $TRAVIS_BUILD_DIR/
  - mkdir -p build && cd build
  - cmake .. 
  - make -j$(nproc)
  - sudo make install

after_success:
  - cd $TRAVIS_BUILD_DIR/example/simple
  - mkdir -p build && cd build
  - cmake ..
  - make

notifications:
    email: false

