version: 1.0.{build}
image: Ubuntu2004
clone_depth: 1

install:
- sudo apt update --yes
- sudo apt install --yes z3 libz3-dev bison flex python python-all-dev

build_script:
- cd $APPVEYOR_BUILD_FOLDER/CacheInstall
- sudo cp -R * /usr
- cd $APPVEYOR_BUILD_FOLDER
- mkdir -p build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release
- make -j$(nproc)
- sudo make install

test_script:
- cd $APPVEYOR_BUILD_FOLDER/example/simple
- mkdir -p build
- cd build
- cmake ..
- make
