version: 1.0.{build}
image: Ubuntu1804
clone_depth: 1

install:
- sudo apt update --yes
- sudo apt install --yes z3 libz3-dev libboost-all-dev

build_script:
- cd $APPVEYOR_BUILD_FOLDER
- bjam -j$(nproc)
